travis:
  secure:
    BINSTAR_TOKEN: JWnNa8jmMId1t8DgDddTh4LVo6Pba2ktZpgP7Yu5NIb3KLdx6hAyA041i4JZT16Otc1mPETn0fv0f75sh8xehEvajxpMua4zcAaHmBPuG/5lWEH7smzsJyNaRHRxo6IOHLmuOiNBaC8IBBJcBwMn/FDGKSDrqJbpXXvtWzNljFvVL/4KGrNyML0PjYl9kNHHWgWn9WNYG2HCjfQi9hoVNl+ThPH/7WOWoIgtoyZUY4MOtFVrjT088H7zMrfPe28VUYQ3CHISr72XxXH1adsWQUlQt1OfHtCbPDl/Js1inOlmtHeD/P9Z9EWQ4AbPPEKnYIdVEjAzH9vh43d+CbG5AuwahBKgd8p5TQsRI0aVPNfp8WrlQwxyMnv2wyKF+LrjSS4QW+aTyFQRcaj56F3jC15g285JAmsv1mDnQhLp/d1iDYYZhjfI9TaNt9IvzznK7yJdnePSguuVH3aZucml4zpV8sKe7c7bg4ByjHV7pzJqHtxJ7c2cJTdjq43IAjQkMosFZpK5eJdeeWDSUW6qiWfcWWwffqkRAadMkViWgg8n7gubuxwsUkwt8jjGNUjudX0PrPVbCsyY0x4f/ct3P+wZ+RWHS30szuLPB7J1RqfGcNR8yIFQqvjf9jgZXt+ZOTrjXCrV8WFSusI0NXax60loqLp+v6n+/pAI2mRm+P8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
